### ISSUE TITLE
I can't install 2 apps using MaterialSearchView on same device !!

### ISSUE THREAD

**Issue by JobGetabu** [Mauker1/MaterialSearchView#164]
#7 still not fixed or Readme is not updated
The application could not be installed: INSTALL_FAILED_CONFLICTING_PROVIDER

**Comment by Mauker1** [comment]
Please refer to the [Setup section on the README](https://github.com/Mauker1/MaterialSearchView#setup). You have to change the `CONTENT_AUTHORITY` String to your own and it **must** be unique for each app, otherwise, it'll result in this conflict you're getting.

If for some reason you're still having this problem feel free to reopen the issue.

**Comment by JobGetabu** [comment]
The manifest file is 
```
<provider
        android:name="br.com.mauker.materialsearchview.db.HistoryProvider"
        android:authorities="br.com.mauker.materialsearchview.searchhistorydatabase"
        android:exported="false"
        android:protectionLevel="signature"
        android:syncable="true"/>
```
this causes `The application could not be installed: INSTALL_FAILED_CONFLICTING_PROVIDER`

**Comment by Mauker1** [comment]
You didn't change the `"br.com.mauker.materialsearchview.searchhistorydatabase"` to your own custom string
