### ISSUE TITLE
How to use it on toolbar？

### ISSUE THREAD

**Issue by sendtion** [Mauker1/MaterialSearchView#17]
How to use it on toolbar？

**Comment by Mauker1** [comment]
I'm assuming you're talking about a generic `Toolbar`, instead of the support `ActionBar`.

You can simply declare your `Toolbar` on your XML file, and add a `Button` to it.

**e.g.:**

```XML
<android.support.v7.widget.Toolbar
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:id="@+id/toolbar"
    android:layout_width="match_parent"
    android:layout_height="wrap_content">

    <Button
        android:id="@+id/myButton"
       android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:text="Click me"
        android:layout_gravity="right" />

</android.support.v7.widget.Toolbar>
```

Then, inside your `Activity` you can get the reference for the `MaterialSearchView` and your toolbar's `Button`:

```Java
MaterialSearchView searchView = (MaterialSearchView) findViewById(R.id.search_view);
Button bt = (Button) findViewById(R.id.myButton);
```

After that, simply add an `onClickListener` to that `Button`, and call `searchView.openSearch()` inside the `onClick(View v)` method.
