### ISSUE TITLE
How can I leave open the search by pressing the enter key? [repeatedly]

### ISSUE THREAD

**Issue by volkdown** [Mauker1/MaterialSearchView#72]
Hello! This answer was not correct. Because when it returns false it will ALWAYS be closed
```java
@Override
            public boolean onQueryTextSubmit(String query) {
                return false;
            }
```

This can be seen from the code:

```java
if(mOnQueryTextListener == null || !mOnQueryTextListener.onQueryTextSubmit(query.toString())) {

                if (mShouldKeepHistory) {
                    saveQueryToDb(query.toString(),System.currentTimeMillis());
                }

                // Refresh the cursor on the adapter,
                // so the new entry will be shown on the next time the user opens the search view.
                refreshAdapterCursor();

                closeSearch();
                mSearchEditText.setText("");
          }
```

I wrote that  we can return true and search view not be closed, but then  suggestion to the database does not save!
You are planning exclude method closeSearch(); in this fragment of code?  And how soon can I expect a new version? Thank you in advance

**Comment by Mauker1** [comment]
The `onSubmitQuery()` method will *always* close the search view when you return `false` because this is the default behavior of the view. But as from version 1.2.0, if you set the return value to `true` it won't save the query in the database, because the behavior should be handled on your listener.
To fix this I could make the `saveQueryToDb()` method public so it'll be possible to handle this behavior yourself.
