### ISSUE TITLE
transparent background and auto dismiss on selecting suggestion

### ISSUE THREAD

**Issue by hisham2007** [Mauker1/MaterialSearchView#9]
this is bug or suggestion.

In Google play, you can see content behind search suggestions. plus, when you select suggestion, search started and search view dismiss automatically

**Comment by AdamMc331** [comment]
You have found a lot of great things today. I wouldn't call this one a bug - it behaves as designed, but we can look into adding a transparent background.

As far as the dismissal, this could be enhanced so that the user can attach their own listener to the ListView. I think these are separate issues, can you change this title to 'add transparent background' and make a new issue for adding ListView OnItemClickListener?

**Comment by AdamMc331** [comment]
You have found a lot of really great things today. We'll consider adding a transparent background.

Regarding the dismissal when you select a description, you can handle this yourself by attaching your own OnItemClickListener, that will do whatever you design it to. Check out [this snippet](https://github.com/Mauker1/MaterialSearchView/blob/master/library/src/main/java/br/com/mauker/materialsearchview/MaterialSearchView.java#L201-L208).

**Comment by AdamMc331** [comment]
Also, regarding the transparent background, that is mentioned already by issue #4 . So, if that clears up your two concerns, I'd like to close this issue.

**Comment by hisham2007** [comment]
Many thanks for great support. I will close it. I will start fixing items I found until you officially update library as I must deliver project this week and your library is the most close to project requirements

**Comment by Mauker1** [comment]
It's closed already, but I'd just like to say that I'm already implementing an API for the transparency. Thanks!
